language: python

python: "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-base-dev python-numpy python-scipy python-opencv

install:
  - pip install -q scikit-learn termcolor
  - easy_install -q SimpleITK

script: nosetests --nocapture -v
